### PR TITLE
Make gub compile on openSuSE 42.3.

### PR DESCRIPTION
**Pull request by lemzwerg**

### CODE REVIEW

**Comment by fedelibre** [comment]
@lemzwerg I've tried your branch (before it was merged) and `make lilypond` still fails with the `KeyError: 'glibc-doc'` error described [here](https://sourceforge.net/p/testlilyissues/issues/5420/) and in #7 .
I'm using LilyDev 0.3 (based on Debian 9).
Have you ever had the same error?

IIUC, it occurs when rebuilding linux-64 and uninstalling glibc-doc.
Some missing dependency in a spec?

**Comment by lemzwerg** [comment]
I didn't have this problem.  My system's python version is 2.7.13; maybe this is of importance.  I'm not a Python guy, so I don't know how to handle this, sorry.

Additionally, I'm only trying to run `make lilypond` right now (i.e., not specifying `LILYPOND_BRANCH`).

**Comment by fedelibre** [comment]
I have the same system's python version:

```
gub@lilydev:~/NewGub$ python -V
Python 2.7.13
```

I've run `make bootstrap` and `make lilypond`.

**Comment by lemzwerg** [comment]
Sorry, I can't help further.  I have zero experience in debugging such a complex Python code.

**Pull request merged**
